cargo-features = ["edition"]

[package]
name = "custom_header"
version = "0.1.0"
authors = ["Rukai <rubickent@gmail.com>"]
edition = '2018'

[dependencies]
ggbasm = { path = "../.." }
failure = "0.1"
